---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dns/external-dns/release.yaml
  - dns/external-dns/namespace.yaml

patches:
  - path: dns/external-dns/patches/settings.yaml
    target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
      name: external-dns
  - path: dns/external-dns/patches/remove-placeholder.yaml
    target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
